### ISSUE TITLE
Timers on DK combo points are munted

### ISSUE THREAD

**Issue by jackuoll** [Tercioo/Plater-Nameplates#123]
**Game and Plater version**
v342-retail

**Describe the bug**
*Steps to Reproduce (what did you do to make the bug happen):*

* Play a death knight
* Enable combo points module
* do several dungeons

*Result (what happens when you follow the steps above):*

* After about a dungeon or two, the timers on the individual combo points will become massive

*Expected (what you think the expected behavior would be when following the steps):*

* Stay the same size

*When the bug started (a date, wow path release, details update, etc)?*

* As soon as I started using the addon

**Screenshots**
Post images of the bug if necessary.

![image](https://user-images.githubusercontent.com/14029546/184642123-35d07e90-fd04-4192-903b-63811e454554.png)

**Comment by cont1nuity** [comment]
Those don't have any cooldown texts on their own by default:
![image](https://user-images.githubusercontent.com/10164755/184823238-32f9c568-0a7d-4c48-bd24-c1c66b1b1c04.png)
Some other addon, possibly OmniCC or similar, is adding them. 
The issue is probably due to the added font and "read animation", the small scale pop. Fonts don't handle scaling changes well.
I'll see if it can be worked around.
