### ISSUE TITLE
Feature: Editing mod options via file instead of interace.

### ISSUE THREAD

**Issue by wwdes** [Tercioo/Plater-Nameplates#163]
The interface for for editing options is very limited and takes a lot of time to accomplish simple tasks. If Plater would save mod options in files we can use text editors to do advanced editing to options much more effectively.

**Comment by Tercioo** [comment]
Show an example of an exported mod text

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: wwdes ***@***.***>
Sent: Saturday, April 8, 2023 9:18:14 PM
To: Tercioo/Plater-Nameplates ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Tercioo/Plater-Nameplates] Feature: Editing mod options via file instead of interace. (Issue #163)


The interface for for editing options is very limited and takes a lot of time to accomplish simple tasks. If Plater would save mod options in files we can use text editors to do advanced editing to options much more effectively.

**Comment by wwdes** [comment]
It's already there. I found it in C:\Program Files (x86)\World of Warcraft\_retail_\WTF\Account\name\SavedVariables\Plater.lua under hook_data options.

**Comment by Tercioo** [comment]
that's correct, and it will work with the client closed when you same 
the file
let me know if you need an "import from table" like weakauras has.


------ Original Message ------
From: "wwdes" ***@***.***>
To: "Tercioo/Plater-Nameplates" ***@***.***>
Cc: "Tercio Jose" ***@***.***>; "Comment" 
***@***.***>
Sent: 09-Apr-23 8:54:01 AM
Subject: Re: [Tercioo/Plater-Nameplates] Feature: Editing mod options 
via file instead of interace. (Issue #163)

**Comment by wwdes** [comment]
I'm thinking maybe instead of importer just a text editor within the interface to edit the options array. Although it's probably not necessary since we already can do it in the file.

**Comment by wwdes** [comment]
slightly of topic. is there any way we can check in a mod if an option has been changed? i have tried with table comparisons but they are prone to fail because of their nature of always being unique..

**Comment by cont1nuity** [comment]
Change from default value?

**Comment by cont1nuity** [comment]
Won't be implemented.
