### ISSUE TITLE
Plater-v570-2-g6665567-Retail-DF-v482-10.2.0 LUA Errors

### ISSUE THREAD

**Issue by IIeTpoc** [Tercioo/Plater-Nameplates#188]
Game Version 10.2.0.52188
Plater Version: Plater-v570-2-g6665567-Retail-DF-v482-10.2.0

1. Install the latest version from CurseForge
2. Log into the game
3. Get following LUA error nonstop

```
26x .../Plater/libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua:535: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "@Plater/libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua"]:535: in function <.../Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:534>
[string "@Plater/libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua"]:644: in function `rangeChecker'
[string "@Plater/Plater.lua"]:849: in function `CheckRange'
[string "@Plater/Plater.lua"]:6560: in function `UpdateTarget'
[string "@Plater/Plater.lua"]:7681: in function `UpdatePlateFrame'
[string "@Plater/Plater.lua"]:3531: in function `func'
[string "@Plater/Plater.lua"]:3784: in function <Plater/Plater.lua:3780>

Locals:
(*temporary) = <function> defined @Plater/libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:600
(*temporary) = "spell"
(*temporary) = "nameplate1"

```

**Comment by cont1nuity** [comment]
Please provide a screenshot of your general settings and give some information which class/spec you are playing.

**Comment by intentionaltypos** [comment]
Just wanted to add that I am getting the same errors specifically on Assassination Rogue.  Using the same profile for other rogue specs (although I need to reloadui after changing specs for errors to go away) or for other characters do not cause the errors.  

Since it was asked for, here are my general settings:

![rogue lua errors settings](https://github.com/Tercioo/Plater-Nameplates/assets/151859191/58df52a2-9eaf-4cdf-857e-7b526bb20af5)

For what it's worth I am also seeing colors behave erratically on just assassination (instead of the typical just yellow and red for mobs I am seeing blues, greens, browns, whites, etc).  They can also change by panning the camera around and having the plates drop off / show up again.

**Comment by cont1nuity** [comment]
Thank you. Can you please try to setup the friendly range check properly and/or disable friendly range check?

**Comment by intentionaltypos** [comment]
For what it's worth - I just updated to Hekili `v10.2.0-1.0.6a` and one of the change log notes was:

```
Temporary bandage on LRC that works for Rogues.
```

It appears to have fixed the issue so it may not have been a plater problem?  I made no changes other than the Hekili update.

**Comment by cont1nuity** [comment]
Might be a rogue only issue with LRC then. Will follow up.

**Comment by cont1nuity** [comment]
https://github.com/WeakAuras/LibRangeCheck-3.0/issues/6

**Comment by cont1nuity** [comment]
The latest alpha should fix this, hopefully.
