### ISSUE TITLE
Debuffs not being tracked on small targets

### ISSUE THREAD

**Issue by itcotta** [Tercioo/Plater-Nameplates#243]
**Game and Plater version**
Which is the game version and Plater version you're using?
Plater-v595-Retail - DF v575 - 11.0.5 

**Describe the bug**
- Steps to Reproduce (what did you do to make the bug happen):
When pulling Mythic Ovi'nax, when the small parasites spawn my debuffs (Flame shock as enhancement shaman) is not being tracked on them.

- Result (what happens when you follow the steps above):
When the small parasites spawn my debuffs (Flame shock as enhancement shaman) is not being tracked on them.

- Expected (what you think the expected behavior would be when following the steps):
Debuffs should be tracked on all enemy nameplates

- When the bug started (a date, wow path release, details update, etc)?
Since first pull

- Additional information:
I'm not sure if this is expected behavior or if its a bug

**Lua Error**
No errors

**Screenshots**
Post images of the bug if necessary.

**Other Information**
If necessary, add more info here.

**Comment by Tercioo** [comment]
Intended, parasites are into a special list for performance.
Edit the list with the addon "Plater Perf Units"


------ Original Message ------
From "Italo Cotta" ***@***.******@***.***>>
To "Tercioo/Plater-Nameplates" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 27-Oct-24 5:55:16 PM
Subject [Tercioo/Plater-Nameplates] Debuffs not being tracked on small targets (Issue #243)


Game and Plater version
Which is the game version and Plater version you're using?
Plater-v595-Retail - DF v575 - 11.0.5

Describe the bug

  *   Steps to Reproduce (what did you do to make the bug happen):
When pulling Mythic Ovi'nax, when the small parasites spawn my debuffs (Flame shock as enhancement shaman) is not being tracked on them.

  *   Result (what happens when you follow the steps above):
When the small parasites spawn my debuffs (Flame shock as enhancement shaman) is not being tracked on them.

  *   Expected (what you think the expected behavior would be when following the steps):
Debuffs should be tracked on all enemy nameplates

  *   When the bug started (a date, wow path release, details update, etc)?
Since first pull

  *   Additional information:
I'm not sure if this is expected behavior or if its a bug

Lua Error
No errors

Screenshots
Post images of the bug if necessary.

Other Information
If necessary, add more info here.

**Comment by cont1nuity** [comment]
Use this addon to manage it:
https://www.curseforge.com/wow/addons/plater-nameplater-performance-units-plugin
