### ISSUE TITLE
BUG - Personal Nameplate sometimes changing position

### ISSUE THREAD

**Issue by LybrialsGit** [Tercioo/Plater-Nameplates#26]
Yet I was not able to reproduce this issue since its happening quite random.
Sometimes, and sometimes often, the personal player resource is changing its position
after mounting or dismounting on or from an automatic flight. 
Its like moving 20 pixels or so from its original position up on the Y-Axis. 
Reloading the interface sets back the position to its correct coordinates.

I have the following Settings:
- Personal Health and Mana Bars: Checked
- Click Through: Checked
- Always Show: Checked

Im using Plater version v8.1.5.265

I recorded a small video where you can see the Bug:
https://youtu.be/jQFoiaKLak8

Its not easy to see, but directly after selecting my flight destination, when the map closes, the plater personal resource bar is changing its position. This is not happening with plater being disabled. Also this is not happening always.

**Comment by LybrialsGit** [comment]
Update: Its reproducable. When you die and become a ghost. It happens always

**Comment by cont1nuity** [comment]
Have you tried re-adjusting the "Fixed position" value? This changes some CVars (Blizzard settings) which should fixate the bar. If those values are not set, which can happen due to the values being stored on blizzards end (not in Plater) and WoW not restoring these values properly on login, the bar will move along your character model (shapeshifts, mounts, size changes, etc.).
