### ISSUE TITLE
NPC Profession Outline

### ISSUE THREAD

**Issue by Solence1** [Tercioo/Plater-Nameplates#48]
Id like to have the option to disable the outline of npc professions when in name only mode. Right now its the only thing keeping me from using it.

**Comment by cont1nuity** [comment]
The option seems to be missing in the configuration... I will put this on my todo-list.
In the meantime, you coud try the following in chat:
/run print(Plater.db.profile.plate_config.friendlynpc.big_actortitle_text_outline)
Remember what this prints in chat, probably "OUTLINE", so that you can reset it if you want.
/run Plater.db.profile.plate_config.friendlynpc.big_actortitle_text_outline="NONE"; ReloadUI();

**Comment by cont1nuity** [comment]
Added settings with #49 - will be available in the next alpha / release.
